#!/usr/bin/env bash
set -u

export PROJECT_ROOT=$(pwd)
echo Project root is set to $PROJECT_ROOT

buildrun() {
    trap popd SIGINT

    pushd $PROJECT_ROOT > /dev/null

    # Compile frontend scripts
    echo Compiling frontend...
    pushd app > /dev/null
    npx tsc
    popd > /dev/null
    echo done

    # Compule backend scripts
    echo Compiling backend...
    pushd server > /dev/null
    npx tsc
    popd > /dev/null
    echo done

    # Run server
    echo Running server...
    node build/server.js

    popd > /dev/null
}